### ISSUE TITLE
크롤러 스케쥴러 만들기

### ISSUE THREAD

**Issue by appetizermonster** [codeforseoul/data#1]

**Comment by hoony-o-1** [comment]
@appetizermonster 님 **Congress-Report** 와 관련된 크롤러 이슈면 해당 레포지토리 이슈로 등록 부탁드려요! :) 여기는 데이터 관련 전반적인 이슈를 다루는게 좋을 것 같아요 :)

**Comment by appetizermonster** [comment]
@thechunsik  넵 잘못 올린 것 같네요 ㅋㅋ
